project:
  type: book
  output-dir: docs

book:
  title: "Dynamic Estimates of Displacement in Disaster Regions"
  author: "Dr. Elisabetta Pietrostefani, Matt Mason, Prof. Francisco Rowe"
  date: today
  chapters:
    - index.qmd
    - overview.qmd
    - workshop.qmd
    - part: probstatement.qmd
      chapters:
        - casestudy.qmd
        - datasets.qmd
        - output.qmd
        - researchareas.qmd
    - part: snowflake.qmd
      chapters:
        - dataaccess.qmd
        - resources.qmd
    - references.qmd

  page-footer:
    left: |
      Dynamic Estimates of Displacement in Disaster Regions by Elisabetta Pietrostefani.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url:  https://pietrostefani.github.io/pop-displacement-disaster
  repo-url: https://github.com/pietrostefani/pop-displacement-disaster
  repo-actions: [edit]
  sharing: [twitter, facebook]
  cover-image: Image2.jpg
  cover-image-alt: |
    Alternative text describing the book cover
  twitter-card:
    creator: "@EPietrostefani"

bibliography: references.bib
margin-header: |
  ![](/logos_web.png)

format:
  html:
    theme: 
    - cosmo
    - r4gds.scss
  pdf:
    documentclass: scrreprt

editor: visual

