# Overview {#sec-overview .unnumbered}

The global challenge of internal displacement, exacerbated by conflict, climate-induced natural hazards and disasters, requires innovative and collaborative approaches to ensure effective responses. As of 2025, displacement continues to surge globally—with 3.7 million people uprooted within Ukraine due to conflict, 18.8 million internally displaced across the Horn of Africa from a mix of drought and violence, and millions more affected annually in South and Southeast Asia, where disasters like cyclones triggered at least 1.8 million displacements in 2023 alone. These figures are a stark reminder of the need for timely, accurate, and spatially detailed data and accessible ways to process it to inform humanitarian action and policy.

This project—led by the University of Liverpool, IOM’s Displacement Tracking Matrix and Snowflake Inc. —compares digital trace data with traditional sources to triangulate and improve displacement estimates.

By leveraging these diverse datasets, the project aims to enhance the precision and reliability of displacement estimates. Using Ukraine as an initial case study, this approach illustrates the ability to generate actionable insights in diverse and complex settings requiring rapid data insights, policy and humanitarian responses. During the hackathon, the framework will be applied to a real-world climate-induced hazard scenario—the Pakistan floods of August 2022—to support timely, data-driven disaster response efforts. This work has been developed in close partnership with operational agencies, ensuring its relevance to real-world needs and its potential to inform evidence-based decision-making.
