# Hackathon {.unnumbered}

Building on work by the University of Liverpool and IOM using digital data to track displacement in **conflict** settings, the Hackathon explores how similar approaches can be applied in the context of **climate-induced natural hazards**. In the aftermath of such disasters, understanding internal displacement patterns is vital for effective humanitarian response.

While **traditional survey-based methods**, like those used by IOM, offer valuable insights in informing operational responses to mitigate the effect of disasters, they often take time to develop and be fully operational. **Digital-trace data present** opportunities for more timely, detailed, and dynamic tracking of population movements before and after climate events, to inform rapid response operations and support spatially targeted interventions.

During the Hackathon, participants will utilise [Meta’s “Facebook Movement During Crisis”](https://dataforgood.facebook.com/dfg/tools/movement-maps) and [“Facebook Population During Crisis”](https://dataforgood.facebook.com/dfg/tools/facebook-population-maps) data derived from mobile phone location records, alongside IOM’s displacement data.

-   The Facebook Movement dataset records the movements of Facebook users, showing how people travel between different areas during a crisis. It includes both the typical movement patterns observed before the crisis and the actual movements during the event, allowing for a comparison between the two.

-   The Population dataset includes information about the number of active Facebook users in a specific area during a crisis, the typical number of active users in that area before the crisis, and the difference between these two values.

By integrating these datasets with traditional sources and socio-economic variables, teams will explore innovative approaches to enhance disaster response, optimise resource allocation, and develop predictive models for future crises.
