# Workshop {#sec-workshop .unnumbered}

A workshop fostering dialogue with key international stakeholders focusing on key added value and limitations of digital trace data for humanitarian action with illustrations. The workshop will be followed by a [hackathon](https://pietrostefani.github.io/pop-displacement-disaster/hackathon.html) where teams use displacement estimates derived from digital trace data for humanitarian action. 

## Day 1

### 9:00–11:00

- **9:00–9:30** – Welcome, Introductions & Agenda – Prof. Francisco Rowe (UoL)
- **9:30–9:50** – Assessing Non-traditional Data Sources – Kate Hokinson (OCHA)  
- **9:50–10:10** – Data and findings from the project – Dr. Elisabetta Pietrostefani (UoL)
- **10:10–10:30** – Lessons learned from the project Digital Trace Data for Population Displacement – Matt Mason (UoL)
- **10:30–10:45** – Questions & Discussion  

<div style="text-align: left;"><strong>10:45–11:00 – Coffee Break</strong></div> 

### 11:00–13:00

- **11:00–11:20** – Using Facebook Movement During Crisis – Dr. Carmen Cabrera-Arnau & Prof. Francisco Rowe  
- **11:20–11:30** – Hackathon Problem Statements - Hong Tran-Jones (IOM DTM)
- **11:30–11:50** – Facebook Population and Movement Data – Matt Mason (UoL)
- **11:50–12:10** – IOM Pakistan Data – Ellen Van de Weghe (IOM Pakistan)
- **12:10–12:40** – Accessing Your Data and Creating an Infographic: A Short Demo using Hackathon Data – Euan Newlands (Snowflake)
- **12:40–13:00** – Questions & Discussion  

### 13:00–14:00

**Networking Lunch**

### 14:00–17:00

- Hackathon Session 1

### 17:00–18:00

- **Team Progress Updates: Goals and Objectives**

### Evening

**18:30–21:00** – Networking Dinner

## Day 2

### 9:00–9:30

- Recap of Hackathon Objectives and Goals - Prof. Francisco Rowe

### 9:00–11:00

- Hackathon Session 2

<div style="text-align: left;"><strong>10:45–11:00 – Coffee Break</strong></div>

### 11:00–13:00

- Hackathon Session 3

### 13:00–14:00

**Working Lunch**

### 14:00–17:00

- Hackathon Final Session

### 17:00–18:00

- **Team Presentations to Panel of Judges**